Landing page UI implementation
AssetMappr/AssetMappr-FE pull request #6
Opened 2023-07-07 22:17 UTC by Ronnie-wof

2023-07-14 00:12 UTC, shashankshk commented on src/App.tsx
> -        {/* <ProtectedRoute component={<HomeScreen />} /> */}
This line should not be deleted. Revert this line as HomeScreen is always in a protected route.

2023-07-14 00:15 UTC, shashankshk commented on src/components/navbar/Navbar.css
Empty file?

2023-07-14 00:16 UTC, shashankshk requested changes
Everything looks good. Just address the mentioned comment to merge this PR

2023-07-26 01:42 UTC, shashankshk approved these changes

2023-07-26 01:42 UTC, n-kumawat approved these changes

2023-07-26 01:43 UTC, merged